export default {
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 18,
  FONT_SIZE_LARGE: 30,
  PRIMARY_COLOR: '#542FAB',
  FONT_WEIGHT_LIGHT: 200,
  FONT_WEIGHT_MEDIUM: 600,
  FONT_WEIGHT_HEAVY: 800,
  MAIN_BACKGROUND_COLOR: '#542FAB',
  BUTTON_FONT_SIZE: 40,
  BUTTON_FONT_COLOR: 'white',
  BUTTON_FONT_WEIGHT: 'bold',
};
